### PR TITLE
Better Prolude Documentation

### PR DESCRIPTION
**Pull request by saralich**
Story details: https://app.clubhouse.io/itprotv/story/55149

### CODE REVIEW

**Review by gera-cameron — APPROVED** [review]
Looks good, but I don't have a ton of experience here. Is there anyway to see how they look locally?

**Comment by goolord** [comment]
run `cabal haddock` and open up the docs it spits out

**Comment by tfausak** [comment]
`stack haddock --open` works too.

**Review by tfausak — CHANGES_REQUESTED** [review]
Unfortunately Haddock fails to build this 😞 

```
Prolude/ByteString.hs:18:1: error: parse error on input ‘import’
   |
18 | import Data.ByteString (ByteString)
   | ^^^^^^
```

It's very picky about how things are organized. The `$section` groups that you have need to come after any imports. So like this:

``` hs
module Example
  ( -- * stuff
    -- $stuff
    module Stuff
  ) where

import Stuff

{- $stuff
You know, for kids!
-}
```

**Comment by saralich** [comment]
How do we feel about module headers? Should each piece of the Prolude pie have one?

**Comment by tfausak** [comment]
I don't think we need module headers at all. That information is in the package description already.

**Review by tfausak — APPROVED** [review]

**Pull request merged**
